const Category = {
	search: "商品搜索，共43838款好物",
	title: [
		{ id: 20001, title: "推荐专区" },
		{ id: 20002, title: "新品专区" },
		{ id: 20003, title: "居家生活" },
		{ id: 20004, title: "服饰鞋包" },
		{ id: 20005, title: "美食酒水" },
		{ id: 20006, title: "个护清洁" },
		{ id: 20007, title: "母婴亲子" },
		{ id: 20008, title: "运动旅游" },
		{ id: 20009, title: "数码家电" },
		{ id: 20010, title: "严选全球" },
	],
	content: {
		"20001": {
			title: [],
			content: {
				"21000": [
					{ text: "员工精选", img: "" },
					{ text: "人气好物", img: "" },
					{ text: "服饰特卖", img: "" },
					{ text: "润秋美食", img: "" },
					{ text: "超级宝贝", img: "" },
					{ text: "回购好物", img: "" },
					{ text: "秋冬床品", img: "" },
					{ text: "99专区", img: "" },
				],
			},
			img: [],
		},
		"20002": {
			title: [],
			content: {
				"21000": [
					{ text: "居家生活新品", img: "" },
					{ text: "服饰鞋包新品", img: "" },
					{ text: "美食酒水新品", img: "" },
					{ text: "个护清洁新品", img: "" },
					{ text: "运动旅行新品", img: "" },
					{ text: "母婴亲子新品", img: "" },
					{ text: "数码家电新品", img: "" },
					{ text: "全球特色新品", img: "" },
				],
			},
			img: [],
		},
		"20003": {
			title: [
				{ id: 21001, title: "口碑好物" },
				{ id: 21002, title: "床上用品" },
				{ id: 21003, title: "家具家装" },
				{ id: 21004, title: "收纳日用" },
				{ id: 21005, title: "家居饰品" },
				{ id: 21006, title: "厨房用品" },
				{ id: 21007, title: "餐具水具" },
				{ id: 21008, title: "宠物生活" },
			],
			content: {
				"21001": [
					{ text: "双11定金购", img: "" },
					{ text: "口碑好物", img: "" },
					{ text: "抑菌防螨", img: "" },
					{ text: "秋冬焕新", img: "" },
					{ text: "北欧原木", img: "" },
					{ text: "收纳好物", img: "" },
					{ text: "餐厨爆款清单", img: "" },
				],
				"21002": [
					{ text: "床品套件", img: "" },
					{ text: "被枕盖毯", img: "" },
					{ text: "床垫床褥", img: "" },
				],
				"21003": [
					{ text: "客餐厅家具", img: "" },
					{ text: "卧室家具", img: "" },
					{ text: "办公书房家具", img: "" },
					{ text: "小件家具", img: "" },
					{ text: "灯具", img: "" },
					{ text: "地毯窗帘", img: "" },
				],
				"21004": [
					{ text: "收纳", img: "" },
					{ text: "晾晒除味", img: "" },
					{ text: "毛巾浴巾", img: "" },
					{ text: "居家拖鞋", img: "" },
					{ text: "家庭医疗", img: "" },
				],
				"21005": [
					{ text: "抱枕靠垫", img: "" },
					{ text: "家饰", img: "" },
					{ text: "居家布艺", img: "" },
				],
				"21006": [
					{ text: "锅具", img: "" },
					{ text: "餐厨配件", img: "" },
					{ text: "刀剪砧板", img: "" },
				],
				"21007": [
					{ text: "餐具", img: "" },
					{ text: "水具杯壶", img: "" },
					{ text: "茶咖酒具", img: "" },
				],
				"21008": [
					{ text: "宠物食品", img: "" },
					{ text: "宠物用品", img: "" },
				],
			},
			img: [],
		},
		"20004": {
			title: [
				{ id: 21001, title: "当季热销" },
				{ id: 21002, title: "男装" },
				{ id: 21003, title: "女装" },
				{ id: 21004, title: "居家内衣" },
				{ id: 21005, title: "运动户外服" },
				{ id: 21006, title: "鞋靴" },
				{ id: 21007, title: "箱包" },
				{ id: 21008, title: "首饰配件" },
				{ id: 21009, title: "系列特辑" },
			],
			content: {
				"21001": [
					{ text: "服装定金购", img: "" },
					{ text: "好物上新", img: "" },
					{ text: "热销爆款", img: "" },
					{ text: "抄底特惠", img: "" },
				],
				"21002": [
					{ text: "男式外套", img: "" },
					{ text: "男式针织衫/卫衣", img: "" },
					{ text: "男式裤装", img: "" },
					{ text: "男式衬衫", img: "" },
					{ text: "男式牛仔", img: "" },
					{ text: "男式T恤/POLO", img: "" },
				],
				"21003": [
					{ text: "女式外套", img: "" },
					{ text: "女式针织衫/卫衣", img: "" },
					{ text: "女式牛仔", img: "" },
					{ text: "女式裤装", img: "" },
					{ text: "女式衬衫", img: "" },
					{ text: "女式T恤/POLO", img: "" },
					{ text: "女式裙装", img: "" },
					{ text: "女式半裙", img: "" },
				],
				"21004": [
					{ text: "女式家居服", img: "" },
					{ text: "女式内衣", img: "" },
					{ text: "女式文胸/套装", img: "" },
					{ text: "男式居家服", img: "" },
					{ text: "男式内衣", img: "" },
					{ text: "男式内裤", img: "" },
					{ text: "女式内裤", img: "" },
					{ text: "女袜/连裤袜", img: "" },
					{ text: "男袜", img: "" },
				],
				"21005": [
					{ text: "女式户外服装", img: "" },
					{ text: "男式户外服装", img: "" },
					{ text: "女式运动外套/卫衣", img: "" },
					{ text: "男式运动外套/卫衣", img: "" },
					{ text: "男式运动裤装", img: "" },
					{ text: "女式运动裤装", img: "" },
					{ text: "男式运动T恤", img: "" },
					{ text: "女式运动T恤", img: "" },
					{ text: "女式运动内衣/泳装", img: "" },
				],
				"21006": [
					{ text: "女鞋", img: "" },
					{ text: "男鞋", img: "" },
					{ text: "拖鞋", img: "" },
					{ text: "鞋配", img: "" },
				],
				"21007": [
					{ text: "行李箱", img: "" },
					{ text: "女式包袋", img: "" },
					{ text: "男式包袋", img: "" },
				],
				"21008": [
					{ text: "奢华珠宝", img: "" },
					{ text: "时尚饰品", img: "" },
					{ text: "围巾手套", img: "" },
					{ text: "帽子发饰", img: "" },
					{ text: "腰带腕表", img: "" },
					{ text: "眼镜墨镜", img: "" },
				],
				"21009": [
					{ text: "免烫系列", img: "" },
					{ text: "棉麻系列", img: "" },
					{ text: "真丝系列", img: "" },
					{ text: "莫代尔系列", img: "" },
					{ text: "海洋环保", img: "" },
				],
			},
			img: [],
		},
		"20005": {
			title: [
				{ id: 21001, title: "美食推荐" },
				{ id: 21002, title: "休闲零食" },
				{ id: 21003, title: "坚果蜜饯" },
				{ id: 21004, title: "冲饮茗茶" },
				{ id: 21005, title: "滋补保健" },
				{ id: 21006, title: "酒水乳饮" },
				{ id: 21007, title: "粮油调味" },
				{ id: 21008, title: "生鲜特色" },
			],
			content: {
				"21001": [
					{ text: "美味双11预售中", img: "" },
					{ text: "10月推荐", img: "" },
					{ text: "美味上新", img: "" },
					{ text: "好味盘点", img: "" },
				],
				"21002": [
					{ text: "饼干糕点", img: "" },
					{ text: "小食糖巧", img: "" },
					{ text: "内类零食", img: "" },
				],
				"21003": [
					{ text: "坚果炒货", img: "" },
					{ text: "蜜饯果干", img: "" },
				],
				"21004": [
					{ text: "冲调饮品", img: "" },
					{ text: "传统茗茶", img: "" },
					{ text: "茗茶礼盒", img: "" },
					{ text: "茶包花茶", img: "" },
				],
				"21005": [
					{ text: "滋补食材", img: "" },
					{ text: "保健品", img: "" },
				],
				"21006": [
					{ text: "乳品饮料", img: "" },
					{ text: "国产酒", img: "" },
					{ text: "进口酒", img: "" },
					{ text: "名酒馆", img: "" },
				],
				"21007": [
					{ text: "米面粮油", img: "" },
					{ text: "方便食品", img: "" },
					{ text: "南北干货", img: "" },
					{ text: "调味酱菜", img: "" },
				],
				"21008": [
					{ text: "水果蔬菜", img: "" },
					{ text: "精选肉类", img: "" },
					{ text: "水产海鲜", img: "" },
					{ text: "冷冻冷藏", img: "" },
					{ text: "网易黑猪", img: "" },
					{ text: "全球美食", img: "" },
				],
			},
			img: [],
		},
		"20006": {
			title: [
				{ id: 21001, title: "好物精选" },
				{ id: 21002, title: "面部护理" },
				{ id: 21003, title: "个人护理" },
				{ id: 21004, title: "彩妆香水" },
				{ id: 21005, title: "个护电器" },
				{ id: 21006, title: "纸品清洁" },
				{ id: 21007, title: "家清卫浴" },
				{ id: 21008, title: "成人用品" },
			],
			content: {
				"21001": [
					{ text: "洗护预售", img: "" },
					{ text: "爆款榜单", img: "" },
					{ text: "新品尝鲜", img: "" },
				],
				"21002": [
					{ text: "基础护肤", img: "" },
					{ text: "卸妆洁面", img: "" },
					{ text: "护肤工具", img: "" },
				],
				"21003": [
					{ text: "洗发护发", img: "" },
					{ text: "身体护理", img: "" },
					{ text: "口腔护理", img: "" },
					{ text: "女性护理", img: "" },
				],
				"21004": [
					{ text: "彩妆修容", img: "" },
					{ text: "香水香氛", img: "" },
					{ text: "美妆工具", img: "" },
				],
				"21005": [
					{ text: "口腔护理电器", img: "" },
					{ text: "面部护理电器", img: "" },
					{ text: "头发护理电器", img: "" },
					{ text: "身体护理电器", img: "" },
				],
				"21006": [
					{ text: "纸品", img: "" },
					{ text: "湿巾", img: "" },
				],
				"21007": [
					{ text: "衣物护理", img: "" },
					{ text: "家庭清洁", img: "" },
					{ text: "餐厨清洁", img: "" },
					{ text: "毛巾浴巾", img: "" },
					{ text: "浴室用品", img: "" },
				],
				"21008": [
					{ text: "避孕套", img: "" },
					{ text: "女用情趣", img: "" },
					{ text: "男用情趣", img: "" },
					{ text: "润滑液", img: "" },
				],
			},
			img: [],
		},
		"20007": [],
		"20008": [],
		"20009": [],
		"20010": [],
	},
};
